version: "3"
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "dynamodata:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    user: root

  dynamodb-init:
    depends_on:
      - dynamodb-local
    image: amazon/aws-cli
    environment:
      AWS_ACCESS_KEY_ID: Aksdjaksdhueiadqwert
      AWS_SECRET_ACCESS_KEY: dshdajksdhajskdhasjkdhasjkdashkjqwertyui
    command: >-
      dynamodb create-table
          --table-name LaBarberLoggedUser
          --attribute-definitions
              AttributeName=credentialId,AttributeType=S
          --key-schema
              AttributeName=credentialId,KeyType=HASH
          --billing-mode PAY_PER_REQUEST
          --endpoint-url http://dynamodb-local:8000 --region us-east-1

  postgres-db:
    hostname: postgres-compose
    image: postgres
    environment:
      POSTGRES_PASSWORD: "teste@2024"
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@test.com"
      PGADMIN_DEFAULT_PASSWORD: "teste@2024"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
  
  # backend:
  #   depends_on:
  #     - postgres-db
  #   build:
  #     context: .
  #     dockerfile: ./LaBarber/Dockerfile
  #     args:
  #       - BUILD_CONFIGURATION=Debug
  #   ports:
  #     - "5270:8080"
  #   environment: 
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionString=Host=postgres-db;Database=barber;User Id=postgres;Password=teste@2024;Pooling=true;
  #     - DynamoLocal:ServiceURL=http://dynamodb-local:8000
  #   links:
      # - dynamodb-local

volumes:
  pgdata:
  dynamodata: