version: "3"
services:
  postgres-db:
    hostname: postgres-compose
    image: postgres
    environment:
      POSTGRES_PASSWORD: "teste@2024"
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "teste@test.com"
      PGADMIN_DEFAULT_PASSWORD: "teste@2024"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
  
  # backend:
  #   depends_on:
  #     - postgres-db
  #   build:
  #     context: .
  #     dockerfile: ./LaBarber/Dockerfile
  #     args:
  #       - BUILD_CONFIGURATION=Debug
  #   ports:
  #     - "5270:8080"
  #   environment: 
  #     - ASPNETCORE_ENVIRONMENT=Development
  #     - ConnectionString=Host=postgres-db;Database=barber;User Id=postgres;Password=teste@2024;Pooling=true;

volumes:
  pgdata: